### ISSUE TITLE
Request for the Scaled Inclusivity script

### ISSUE THREAD

**Issue by JinFeng-Wu** [eglerean/hfASDmodules#1]
Hi, I just read your ASD paper, well done. But I didn't't find the python script for SI, which is very important in your study, can you release or share it? Thank you.

**Comment by eglerean** [comment]
Hi Michael

the code for the Scaled Inclusivity (SI) can be found at https://github.com/rmkujala/brainnets 
This was a joint effort with the people maintaining that repo, so I recommend searching there for the actual function to compute SI.

In practice: obtain a parcellation for each of your subjects that becomes a list of integers of cluster IDs. Then for each node, compute the scaled inclusivity with the script there. Then what we did in the paper is that for a consensus module you can compute its average SI between two subjects so that you can look  if the similarity is related to inter-individual differences (e.g. AQ score in our case).

If you need a more detailed explanation please let me know.
